//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taskt.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Активировать окно")]
        public string ActivateWindow_Name {
            get {
                return ((string)(this["ActivateWindow_Name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Комманды окон")]
        public string Window_Group {
            get {
                return ((string)(this["Window_Group"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Добавить к переменной")]
        public string AddToVariable_Name {
            get {
                return ((string)(this["AddToVariable_Name"]));
            }
            set {
                this["AddToVariable_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Начать цикл")]
        public string BeginContinousLoop_Name {
            get {
                return ((string)(this["BeginContinousLoop_Name"]));
            }
            set {
                this["BeginContinousLoop_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Новая переменная")]
        public string AddVariable_Name {
            get {
                return ((string)(this["AddVariable_Name"]));
            }
            set {
                this["AddVariable_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Начать цикл данных Excel")]
        public string BeginExcelDatasetLoop_Name {
            get {
                return ((string)(this["BeginExcelDatasetLoop_Name"]));
            }
            set {
                this["BeginExcelDatasetLoop_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Начать условную ветку")]
        public string BeginIf_Name {
            get {
                return ((string)(this["BeginIf_Name"]));
            }
            set {
                this["BeginIf_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Начать цикл по элементам списка")]
        public string BeginListLoop_Name {
            get {
                return ((string)(this["BeginListLoop_Name"]));
            }
            set {
                this["BeginListLoop_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Начать цикл, выполняющийся несколько раз")]
        public string BeginNumberOfTimesLoop_Name {
            get {
                return ((string)(this["BeginNumberOfTimesLoop_Name"]));
            }
            set {
                this["BeginNumberOfTimesLoop_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Получить текст из буфера обмена")]
        public string ClipboardGetText_Name {
            get {
                return ((string)(this["ClipboardGetText_Name"]));
            }
            set {
                this["ClipboardGetText_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Добавить текст в буфер обмена")]
        public string ClipboardSetText_Name {
            get {
                return ((string)(this["ClipboardSetText_Name"]));
            }
            set {
                this["ClipboardSetText_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Закрыть окно")]
        public string CloseWindow_Name {
            get {
                return ((string)(this["CloseWindow_Name"]));
            }
            set {
                this["CloseWindow_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Комментарий")]
        public string Comment_Name {
            get {
                return ((string)(this["Comment_Name"]));
            }
            set {
                this["Comment_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Запустить запрос к базе данных")]
        public string DatabaseRunQuery_Name {
            get {
                return ((string)(this["DatabaseRunQuery_Name"]));
            }
            set {
                this["DatabaseRunQuery_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Посчитать дату")]
        public string DateCalculation_Name {
            get {
                return ((string)(this["DateCalculation_Name"]));
            }
            set {
                this["DateCalculation_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Удалить файл")]
        public string DeleteFile_Name {
            get {
                return ((string)(this["DeleteFile_Name"]));
            }
            set {
                this["DeleteFile_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Альтернативная ветка")]
        public string Else_Name {
            get {
                return ((string)(this["Else_Name"]));
            }
            set {
                this["Else_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Закончить условную ветку")]
        public string EndIf_Name {
            get {
                return ((string)(this["EndIf_Name"]));
            }
            set {
                this["EndIf_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Закончить цикл")]
        public string EndLoop_Name {
            get {
                return ((string)(this["EndLoop_Name"]));
            }
            set {
                this["EndLoop_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Переменная среды")]
        public string EnvironmentVariable_Name {
            get {
                return ((string)(this["EnvironmentVariable_Name"]));
            }
            set {
                this["EnvironmentVariable_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ветвь ошибки")]
        public string ErrorHandling_Name {
            get {
                return ((string)(this["ErrorHandling_Name"]));
            }
            set {
                this["ErrorHandling_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Активировать лист Excel")]
        public string ExcelActivateSheet_Name {
            get {
                return ((string)(this["ExcelActivateSheet_Name"]));
            }
            set {
                this["ExcelActivateSheet_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Добавить файл Excel")]
        public string ExcelAddWorkbook_Name {
            get {
                return ((string)(this["ExcelAddWorkbook_Name"]));
            }
            set {
                this["ExcelAddWorkbook_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Закрыть Excel")]
        public string ExcelCloseApplication_Name {
            get {
                return ((string)(this["ExcelCloseApplication_Name"]));
            }
            set {
                this["ExcelCloseApplication_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Создать набор данных Excel")]
        public string ExcelCreateDataSet_Name {
            get {
                return ((string)(this["ExcelCreateDataSet_Name"]));
            }
            set {
                this["ExcelCreateDataSet_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Удалить ячейку Excel")]
        public string ExcelDeleteCell_Name {
            get {
                return ((string)(this["ExcelDeleteCell_Name"]));
            }
            set {
                this["ExcelDeleteCell_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelDeleteRow_Name {
            get {
                return ((string)(this["ExcelDeleteRow_Name"]));
            }
            set {
                this["ExcelDeleteRow_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelGetCell_Name {
            get {
                return ((string)(this["ExcelGetCell_Name"]));
            }
            set {
                this["ExcelGetCell_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelGetLastRow_Name {
            get {
                return ((string)(this["ExcelGetLastRow_Name"]));
            }
            set {
                this["ExcelGetLastRow_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelGoToCell_Name {
            get {
                return ((string)(this["ExcelGoToCell_Name"]));
            }
            set {
                this["ExcelGoToCell_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelOpenWorkbook_Name {
            get {
                return ((string)(this["ExcelOpenWorkbook_Name"]));
            }
            set {
                this["ExcelOpenWorkbook_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelRunMacro_Name {
            get {
                return ((string)(this["ExcelRunMacro_Name"]));
            }
            set {
                this["ExcelRunMacro_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelSaveAs_Name {
            get {
                return ((string)(this["ExcelSaveAs_Name"]));
            }
            set {
                this["ExcelSaveAs_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelSave_Name {
            get {
                return ((string)(this["ExcelSave_Name"]));
            }
            set {
                this["ExcelSave_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelSetCell_Name {
            get {
                return ((string)(this["ExcelSetCell_Name"]));
            }
            set {
                this["ExcelSetCell_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExecuteDLL_Name {
            get {
                return ((string)(this["ExecuteDLL_Name"]));
            }
            set {
                this["ExecuteDLL_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExitLoop_Name {
            get {
                return ((string)(this["ExitLoop_Name"]));
            }
            set {
                this["ExitLoop_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FormatDataCommand_Name {
            get {
                return ((string)(this["FormatDataCommand_Name"]));
            }
            set {
                this["FormatDataCommand_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GetData_Name {
            get {
                return ((string)(this["GetData_Name"]));
            }
            set {
                this["GetData_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GetWordCount_Name {
            get {
                return ((string)(this["GetWordCount_Name"]));
            }
            set {
                this["GetWordCount_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GetWordLength_Name {
            get {
                return ((string)(this["GetWordLength_Name"]));
            }
            set {
                this["GetWordLength_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HTMLInputCommand_Name {
            get {
                return ((string)(this["HTMLInputCommand_Name"]));
            }
            set {
                this["HTMLInputCommand_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HTTPQueryResultCommand {
            get {
                return ((string)(this["HTTPQueryResultCommand"]));
            }
            set {
                this["HTTPQueryResultCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HTTPRequest_Name {
            get {
                return ((string)(this["HTTPRequest_Name"]));
            }
            set {
                this["HTTPRequest_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IEBrowserClose_Name {
            get {
                return ((string)(this["IEBrowserClose_Name"]));
            }
            set {
                this["IEBrowserClose_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IEBrowserCreate_Name {
            get {
                return ((string)(this["IEBrowserCreate_Name"]));
            }
            set {
                this["IEBrowserCreate_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IEBrowserElementAction_Name {
            get {
                return ((string)(this["IEBrowserElementAction_Name"]));
            }
            set {
                this["IEBrowserElementAction_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IEBrowserFindBrowser_Name {
            get {
                return ((string)(this["IEBrowserFindBrowser_Name"]));
            }
            set {
                this["IEBrowserFindBrowser_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IEBrowserNavigateURL_Name {
            get {
                return ((string)(this["IEBrowserNavigateURL_Name"]));
            }
            set {
                this["IEBrowserNavigateURL_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageRecognition_Name {
            get {
                return ((string)(this["ImageRecognition_Name"]));
            }
            set {
                this["ImageRecognition_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogData_Name {
            get {
                return ((string)(this["LogData_Name"]));
            }
            set {
                this["LogData_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MessageBox_Name {
            get {
                return ((string)(this["MessageBox_Name"]));
            }
            set {
                this["MessageBox_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModifyVariable_Name {
            get {
                return ((string)(this["ModifyVariable_Name"]));
            }
            set {
                this["ModifyVariable_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MoveFile_Name {
            get {
                return ((string)(this["MoveFile_Name"]));
            }
            set {
                this["MoveFile_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MoveWindow_Name {
            get {
                return ((string)(this["MoveWindow_Name"]));
            }
            set {
                this["MoveWindow_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NLGCreateInstance_Name {
            get {
                return ((string)(this["NLGCreateInstance_Name"]));
            }
            set {
                this["NLGCreateInstance_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NLGGeneratePhrase_Name {
            get {
                return ((string)(this["NLGGeneratePhrase_Name"]));
            }
            set {
                this["NLGGeneratePhrase_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NLGSetParameter_Name {
            get {
                return ((string)(this["NLGSetParameter_Name"]));
            }
            set {
                this["NLGSetParameter_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OCR_Name {
            get {
                return ((string)(this["OCR_Name"]));
            }
            set {
                this["OCR_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OSVariable_Name {
            get {
                return ((string)(this["OSVariable_Name"]));
            }
            set {
                this["OSVariable_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ParseJSONArray_Name {
            get {
                return ((string)(this["ParseJSONArray_Name"]));
            }
            set {
                this["ParseJSONArray_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ParseJson_Name {
            get {
                return ((string)(this["ParseJson_Name"]));
            }
            set {
                this["ParseJson_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Pause_Name {
            get {
                return ((string)(this["Pause_Name"]));
            }
            set {
                this["Pause_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PDFTextExtractor_Name {
            get {
                return ((string)(this["PDFTextExtractor_Name"]));
            }
            set {
                this["PDFTextExtractor_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReadTextFile_Name {
            get {
                return ((string)(this["ReadTextFile_Name"]));
            }
            set {
                this["ReadTextFile_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Команды окон")]
        public string WindowsGroup_Name {
            get {
                return ((string)(this["WindowsGroup_Name"]));
            }
            set {
                this["WindowsGroup_Name"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Execute DLL) 执行DLL")]
        public string Execute_DLL_cn {
            get {
                return ((string)(this["Execute_DLL_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Execute REST API)执行REST API")]
        public string Execute_REST_API_cn {
            get {
                return ((string)(this["Execute_REST_API_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(HTTP Request)HTTP请求")]
        public string HTTP_Request_cn {
            get {
                return ((string)(this["HTTP_Request_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(HTTP Result Query)HTTP结果查询")]
        public string HTTP_Result_Query_cn {
            get {
                return ((string)(this["HTTP_Result_Query_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Date Calculation)日期计算")]
        public string Date_Calculation_cn {
            get {
                return ((string)(this["Date_Calculation_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Format Data)格式数据")]
        public string Format_Data_cn {
            get {
                return ((string)(this["Format_Data_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Get Word Count)得到字数")]
        public string Get_Word_Count_cn {
            get {
                return ((string)(this["Get_Word_Count_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Get Word Length)得到字长")]
        public string Get_Word_Length_cn {
            get {
                return ((string)(this["Get_Word_Length_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Log Data)日志数据")]
        public string Log_Data_cn {
            get {
                return ((string)(this["Log_Data_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Modify Variable)修改变量")]
        public string Modify_Variable_cn {
            get {
                return ((string)(this["Modify_Variable_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Parse JSON Array)解析JSON数组")]
        public string Parse_JSON_Array_cn {
            get {
                return ((string)(this["Parse_JSON_Array_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Parse JSON Object)解析JSON对象")]
        public string Parse_JSON_Object_cn {
            get {
                return ((string)(this["Parse_JSON_Object_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(PDF Extraction)PDF提取")]
        public string PDF_Extraction_cn {
            get {
                return ((string)(this["PDF_Extraction_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(RegEx Extraction)RegEx提取")]
        public string RegEx_Extraction_cn {
            get {
                return ((string)(this["RegEx_Extraction_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Replace Text)替换文字")]
        public string Replace_Text_cn {
            get {
                return ((string)(this["Replace_Text_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Split Text)替换文字")]
        public string Split_Text_cn {
            get {
                return ((string)(this["Split_Text_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Substring)子")]
        public string Substring_cn {
            get {
                return ((string)(this["Substring_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Text Extraction)文本提取")]
        public string Text_Extraction_cn {
            get {
                return ((string)(this["Text_Extraction_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Error handling)错误处理")]
        public string Error_handling_cn {
            get {
                return ((string)(this["Error_handling_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Get BotStore Data)获取BotStore数据")]
        public string Get_BotStore_Data_cn {
            get {
                return ((string)(this["Get_BotStore_Data_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Pause Script)暂停脚本")]
        public string Pause_Script_cn {
            get {
                return ((string)(this["Pause_Script_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Set Engine Delay)设置引擎延迟")]
        public string Set_Engine_Delay_cn {
            get {
                return ((string)(this["Set_Engine_Delay_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Stopwatch)跑表")]
        public string Stopwatch_cn {
            get {
                return ((string)(this["Stopwatch_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Upload BotStore Data)上传BotStore数据")]
        public string Upload_BotStore_Data_cn {
            get {
                return ((string)(this["Upload_BotStore_Data_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Activate Sheet)激活工作表")]
        public string Activate_Sheet_cn {
            get {
                return ((string)(this["Activate_Sheet_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Add Workbook)添加工作簿")]
        public string Add_Workbook_cn {
            get {
                return ((string)(this["Add_Workbook_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Close Excel Application)关闭Excel应用程序")]
        public string Close_Excel_Application_cn {
            get {
                return ((string)(this["Close_Excel_Application_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Create Dataset)创建数据集")]
        public string Create_Dataset_cn {
            get {
                return ((string)(this["Create_Dataset_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Create Excel Application)创建Excel应用程序")]
        public string Create_Excel_Application_cn {
            get {
                return ((string)(this["Create_Excel_Application_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Delete Cell)删除单元格")]
        public string Delete_Cell_cn {
            get {
                return ((string)(this["Delete_Cell_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Delete Row)删除行")]
        public string Delete_Row_cn {
            get {
                return ((string)(this["Delete_Row_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Get Cell)获取细胞")]
        public string Get_Cell_cn {
            get {
                return ((string)(this["Get_Cell_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Get Last Row Index)获取最后一行索引")]
        public string Get_Last_Row_Index_cn {
            get {
                return ((string)(this["Get_Last_Row_Index_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Go To Cell)转到细胞")]
        public string Go_To_Cell_cn {
            get {
                return ((string)(this["Go_To_Cell_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Open Workbook)打开工作簿")]
        public string Open_Workbook_cn {
            get {
                return ((string)(this["Open_Workbook_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Run Macro)运行宏")]
        public string Run_Macro_cn {
            get {
                return ((string)(this["Run_Macro_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Save Workbook)保存工作簿")]
        public string Save_Workbook_cn {
            get {
                return ((string)(this["Save_Workbook_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Save Workbook As)将工作簿另存为")]
        public string Save_Workbook_As_cn {
            get {
                return ((string)(this["Save_Workbook_As_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Set Cell)设置单元格")]
        public string Set_Cell_cn {
            get {
                return ((string)(this["Set_Cell_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Delete File)删除文件")]
        public string Delete_File_cn {
            get {
                return ((string)(this["Delete_File_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Move/Copy File)移动/复制文件")]
        public string Move_Copy_File_cn {
            get {
                return ((string)(this["Move_Copy_File_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Rename File)重新命名文件")]
        public string Rename_File_cn {
            get {
                return ((string)(this["Rename_File_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Wait For File)等待文件")]
        public string Wait_For_File_cn {
            get {
                return ((string)(this["Wait_For_File_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Close Browser)关闭浏览器")]
        public string Close_Browser_cn {
            get {
                return ((string)(this["Close_Browser_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Create Browser)创建浏览器")]
        public string Create_Browser_cn {
            get {
                return ((string)(this["Create_Browser_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Element Action)元素行动")]
        public string Element_Action_cn {
            get {
                return ((string)(this["Element_Action_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Find Browser)查找浏览器")]
        public string Find_Browser_cn {
            get {
                return ((string)(this["Find_Browser_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Navigate to URL)导航到URL")]
        public string Navigate_to_URL_cn {
            get {
                return ((string)(this["Navigate_to_URL_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Begin If)从如果开始")]
        public string Begin_If_cn {
            get {
                return ((string)(this["Begin_If_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Else)其他")]
        public string Else_cn {
            get {
                return ((string)(this["Else_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(End If)万一")]
        public string End_If_cn {
            get {
                return ((string)(this["End_If_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Image Recognition)图像识别")]
        public string Image_Recognition_cn {
            get {
                return ((string)(this["Image_Recognition_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Perform OCR)执行OCR")]
        public string Perform_OCR_cn {
            get {
                return ((string)(this["Perform_OCR_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Take Screenshot)截图")]
        public string Take_Screenshot_cn {
            get {
                return ((string)(this["Take_Screenshot_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Prompt for HTML Input)提示输入HTML")]
        public string Prompt_for_HTML_Input_cn {
            get {
                return ((string)(this["Prompt_for_HTML_Input_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Prompt for Input)提示输入")]
        public string Prompt_for_Input_cn {
            get {
                return ((string)(this["Prompt_for_Input_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Send Advanced Keystrokes)发送高级击键")]
        public string Send_Advanced_Keystrokes_cn {
            get {
                return ((string)(this["Send_Advanced_Keystrokes_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Send Keystrokes)发送击键")]
        public string Send_Keystrokes_cn {
            get {
                return ((string)(this["Send_Keystrokes_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Send Mouse Click)发送鼠标单击")]
        public string Send_Mouse_Click_cn {
            get {
                return ((string)(this["Send_Mouse_Click_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Send Mouse Move)发送鼠标移动")]
        public string Send_Mouse_Move_cn {
            get {
                return ((string)(this["Send_Mouse_Move_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(UI Automation)UI自动化")]
        public string UI_Automation_cn {
            get {
                return ((string)(this["UI_Automation_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(End Loop)结束循环")]
        public string End_Loop_cn {
            get {
                return ((string)(this["End_Loop_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Exit Loop)退出循环")]
        public string Exit_Loop_cn {
            get {
                return ((string)(this["Exit_Loop_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Loop Continuously)循环不断")]
        public string Loop_Continuously_cn {
            get {
                return ((string)(this["Loop_Continuously_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Loop Dataset)循环数据集")]
        public string Loop_Dataset_cn {
            get {
                return ((string)(this["Loop_Dataset_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Loop List)循环列表")]
        public string Loop_List_cn {
            get {
                return ((string)(this["Loop_List_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Loop Number Of Times)循环次数")]
        public string Loop_Number_Of_Times_cn {
            get {
                return ((string)(this["Loop_Number_Of_Times_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Add Code Comment)添加代码注释")]
        public string Add_Code_Comment_cn {
            get {
                return ((string)(this["Add_Code_Comment_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Get Clipboard Text)获取剪贴板文本")]
        public string Get_Clipboard_Text_cn {
            get {
                return ((string)(this["Get_Clipboard_Text_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Send SMTP Email)发送SMTP电子邮件")]
        public string Send_SMTP_Email_cn {
            get {
                return ((string)(this["Send_SMTP_Email_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Sequence Command)序列命令")]
        public string Sequence_Command_cn {
            get {
                return ((string)(this["Sequence_Command_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Set Clipboard Text)设置剪贴板文本")]
        public string Set_Clipboard_Text_cn {
            get {
                return ((string)(this["Set_Clipboard_Text_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Show Message)显示消息")]
        public string Show_Message_cn {
            get {
                return ((string)(this["Show_Message_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Create NLG Instance)创建NLG实例")]
        public string Create_NLG_Instance_cn {
            get {
                return ((string)(this["Create_NLG_Instance_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Generate NLG Phrase)生成NLG短语")]
        public string Generate_NLG_Phrase_cn {
            get {
                return ((string)(this["Generate_NLG_Phrase_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Set NLG Parameter)设置NLG参数")]
        public string Set_NLG_Parameter_cn {
            get {
                return ((string)(this["Set_NLG_Parameter_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Run Custom Code)运行自定义代码")]
        public string Run_Custom_Code_cn {
            get {
                return ((string)(this["Run_Custom_Code_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Run Script)运行脚本")]
        public string Run_Script_cn {
            get {
                return ((string)(this["Run_Script_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Start Process)开始流程")]
        public string Start_Process_cn {
            get {
                return ((string)(this["Start_Process_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Stop Process)停止流程")]
        public string Stop_Process_cn {
            get {
                return ((string)(this["Stop_Process_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Environment Variable)环境变量")]
        public string Environment_Variable_cn {
            get {
                return ((string)(this["Environment_Variable_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Launch Remote Desktop)启动远程桌面")]
        public string Launch_Remote_Desktop_cn {
            get {
                return ((string)(this["Launch_Remote_Desktop_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(OS Variable)OS变量")]
        public string OS_Variable_cn {
            get {
                return ((string)(this["OS_Variable_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(System Action)系统行动")]
        public string System_Action_cn {
            get {
                return ((string)(this["System_Action_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Run Task)运行任务")]
        public string Run_Task_cn {
            get {
                return ((string)(this["Run_Task_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Stop Current Task)停止当前任务")]
        public string Stop_Current_Task_cn {
            get {
                return ((string)(this["Stop_Current_Task_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Read Text File)阅读文本文件")]
        public string Read_Text_File_cn {
            get {
                return ((string)(this["Read_Text_File_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Write Text File)写文本文件")]
        public string Write_Text_File_cn {
            get {
                return ((string)(this["Write_Text_File_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Add To Variable)添加到变量")]
        public string Add_To_Variable_cn {
            get {
                return ((string)(this["Add_To_Variable_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(New Variable)新变量")]
        public string New_Variable_cn {
            get {
                return ((string)(this["New_Variable_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Set Variable)设置变量")]
        public string Set_Variable_cn {
            get {
                return ((string)(this["Set_Variable_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Set Variable Index)设置变量索引")]
        public string Set_Variable_Index_cn {
            get {
                return ((string)(this["Set_Variable_Index_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Close Browser)关闭浏览器")]
        public string Close_Web_Browser_cn {
            get {
                return ((string)(this["Close_Web_Browser_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Create Browser)创建浏览器")]
        public string Create_Web_Browser_cn {
            get {
                return ((string)(this["Create_Web_Browser_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Element Action)元素行动")]
        public string Element_Web_Action_cn {
            get {
                return ((string)(this["Element_Web_Action_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Execute Script)执行脚本")]
        public string Execute_Script_cn {
            get {
                return ((string)(this["Execute_Script_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Navigate Back)导航回来")]
        public string Navigate_Back_cn {
            get {
                return ((string)(this["Navigate_Back_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Navigate Forward)向前导航")]
        public string Navigate_Forward_cn {
            get {
                return ((string)(this["Navigate_Forward_cn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Navigate to URL)导航到URL")]
        public string Navigate_to_Web_URL_cn {
            get {
                return ((string)(this["Navigate_to_Web_URL_cn"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Refresh)刷新")]
        public string Refresh_cn {
            get {
                return ((string)(this["Refresh_cn"]));
            }
            set {
                this["Refresh_cn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Activate Window)激活窗口")]
        public string Activate_Window_cn {
            get {
                return ((string)(this["Activate_Window_cn"]));
            }
            set {
                this["Activate_Window_cn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Close Window)关闭窗口")]
        public string Close_Window_cn {
            get {
                return ((string)(this["Close_Window_cn"]));
            }
            set {
                this["Close_Window_cn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Move Window)移动窗口")]
        public string Move_Window_cn {
            get {
                return ((string)(this["Move_Window_cn"]));
            }
            set {
                this["Move_Window_cn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Resize Window)调整窗口大小")]
        public string Resize_Window_cn {
            get {
                return ((string)(this["Resize_Window_cn"]));
            }
            set {
                this["Resize_Window_cn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Set Window State)设置窗口状态")]
        public string Set_Window_State_cn {
            get {
                return ((string)(this["Set_Window_State_cn"]));
            }
            set {
                this["Set_Window_State_cn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Wait For Window To Exist)等待窗口存在")]
        public string Wait_For_Window_To_Exist_cn {
            get {
                return ((string)(this["Wait_For_Window_To_Exist_cn"]));
            }
            set {
                this["Wait_For_Window_To_Exist_cn"] = value;
            }
        }
    }
}
